###############################################################################
#
# Auto IRC flag module configuration
#
###############################################################################

::dZSbot::Config::Set ircflags.enabled 0
::dZSbot::Config::Set ircflags.channels {#pre #spam #monstra #staff}

# Rules use Eggdrop handle flags.
# Format: {mode {flags} {optional channels}}
#
# Examples:
#   Give ops/masters +o in staff.
#   Give known users with +v voice in public channels.
#
::dZSbot::Config::Set ircflags.rules {
    {o {n m o} {#staff}}
    {v {v} {#pre #spam #monstra}}
}
