###############################################################################
#
# NFO module configuration
#
###############################################################################

::dZSbot::Config::Set nfo.storage [file join $::dZSbot::Root database nfo]
