###############################################################################
#
# Retention module configuration
#
###############################################################################

::dZSbot::Config::Set retention.enabled 1
