###############################################################################
#
# Site operations module configuration
#
###############################################################################

::dZSbot::Config::Set site.commands.df.enabled 1
::dZSbot::Config::Set site.commands.bw.enabled 1
::dZSbot::Config::Set site.commands.reply_target "channel"
::dZSbot::Config::Set site.commands.bw.show_idle 0

# Configure disk free sections as name/path pairs.
#
# Example:
# ::dZSbot::Config::Set site.df.sections {
#     {MOVIES "D:/ioFTPD/FTP-ROOT-DIR/MOVIES"}
#     {TV "\\\\nas\\site\\TV"}
#     {MUSIC "E:/FTP/MUSIC"}
# }
::dZSbot::Config::Set site.df.sections {}
