###############################################################################
#
# TV module configuration
#
###############################################################################

::dZSbot::Config::Set tv.provider ""
::dZSbot::Config::Set tv.announce.enabled 1
::dZSbot::Config::Set tv.announce.sections {TV}
::dZSbot::Config::Set tv.announce.pre_channel "#pre"
::dZSbot::Config::Set tv.announce.staff_channel "#staff"
