###############################################################################
#
# Upload announce module configuration
#
###############################################################################

::dZSbot::Config::Set upload.announce.enabled 1
::dZSbot::Config::Set upload.announce.channel "#pre"
::dZSbot::Config::Set upload.announce.events {newdir first half leader complete badfile nfo doublesfv speedtest incomplete}
::dZSbot::Config::Set upload.announce.event.newdir.enabled 1
::dZSbot::Config::Set upload.announce.event.first.enabled 1
::dZSbot::Config::Set upload.announce.event.half.enabled 1
::dZSbot::Config::Set upload.announce.event.racer.enabled 0
::dZSbot::Config::Set upload.announce.event.leader.enabled 1
::dZSbot::Config::Set upload.announce.event.complete.enabled 1
::dZSbot::Config::Set upload.announce.event.badfile.enabled 1
::dZSbot::Config::Set upload.announce.event.nfo.enabled 1
::dZSbot::Config::Set upload.announce.event.doublesfv.enabled 1
::dZSbot::Config::Set upload.announce.event.speedtest.enabled 1
::dZSbot::Config::Set upload.announce.event.incomplete.enabled 1
::dZSbot::Config::Set upload.announce.sections {MOVIES TV MUSIC MP3 FLAC AUDIOBOOKS GAMES PC CONSOLE EBOOKS}
