###############################################################################
#
# Upload announce module configuration
#
###############################################################################

::dZSbot::Config::Set upload.announce.enabled 1
::dZSbot::Config::Set upload.announce.channel "#pre"
::dZSbot::Config::Set upload.announce.events {newdir complete}
::dZSbot::Config::Set upload.announce.sections {MOVIES TV MUSIC MP3 FLAC AUDIOBOOKS GAMES PC CONSOLE EBOOKS}
